# Changes here will be overwritten by Copier
_commit: 8d1b0cc
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2024'
documentation: true
email: nick@koston.org
full_name: J. Nick Koston
github_username: bdraco
has_cli: false
initial_commit: true
open_source_license: GNU General Public License v3
package_name: aiodhcpwatcher
project_name: aiodhcpwatcher
project_short_description: Watch for DHCP packets with asyncio
project_slug: aiodhcpwatcher
run_poetry_install: true
setup_github: true
setup_pre_commit: true

